title: Tay Tyn Long # your name (or website title) here
logo: "/images/oooo.plus_139.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Tyn is a data analyst with a strong proficiency in Python, SQL and Tableau. He has experience in client-facing consultation and subject matter specific engineering research. He is looking for a role as a data analyst, bringing actionable and effective insights to your organisation.<br>
  <br><br>
  <a href="https://https://www.linkedin.com/in/tynlong-tay/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-midnight
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
